### ISSUE TITLE
Hint picker is too eager

### ISSUE THREAD

**Issue by corwin-of-amber** [ejgallego/CodeMirror-TeX-input#2]
Problem: pressing Space is bound to picking the active hint in completionActive. This is pretty good for the TeX completion (where you really only want things from the list), but the TeX-input addon enables it **globally**. This is rather a nuisance for company-coq, where the hints are only a suggestion and the list is not always comprehensive, and it's quite common to want to type, e.g., `in` where the library contains a definition named `invariant`, and the user does not expect `invariant` to be automatically picked, replacing `in`, upon pressing Space.

I will send a patch.

**Comment by ejgallego** [comment]
Oh, indeed! I introduced this behavior as indeed IMHO I think you want it when using a TeX symbol, but should be disabled for hints coming from other sources yes.
